title: Technonerds
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.734767
  brandStrength: 0.5053763
  lightness: 0.7616488
  brandColors:
    - '#0183AD'
    - '#FEFEFE'
    - '#D5D5D5'
    - '#92C3CE'
    - '#64AAC1'
  rhythmicContrast: 0.6182796
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Technonerds
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3387097
layout_spectrum: 0.4946237
