name: Technonerds
favicon: null
layout_spectrum: 0.4928315
typography_spectrum: 0.51663
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Technonerds
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0183AD'
    - '#FEFEFE'
    - '#D5D5D5'
    - '#92C3CE'
    - '#64AAC1'
  brandStrength: 0.5053763
  lightness: 0.2598566
  saturation: 0.08114866
  rhythmicContrast: 0.01391251
purpose: []
